install.packages(c("usethis", "devtools", "roxygen2", "testthat"))
library(usethis)
use_r("simultaneous_ci")
use_testthat()
use_roxygen_md()
use_github()
use_readme_rmd()
use_package("MASS")
use_package("stats")
use_github_action("check-standard")
library(usethis)
usethis::use_package("pbapply", "Suggests")
renv::install("pbapply")
renv::snapshot()
devtools::document()
